name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -r --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with: 
        name: docker-volbackup
        path: ./target/release/volbackup
      
