name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: actions/checkout@v3
      run: cargo build -r --verbose
    - name: Upload artifact
      uses: actions/upload-artiface@v3
      with: 
        name: docker-volbackup
        path: ./target/release/volbackup
      
